version: '3.8'

services:
  parser1:
    build: ./
    depends_on:
      wgcf1:
        condition: service_healthy
    restart: "no"
    volumes:
      - ./:/code
    environment:
      - "TZ=Asia/Aqtau"
    network_mode: service:wgcf1
    stop_grace_period: 2m
    command: python3 -m parser_2gis --url /code/input1 --output /code/output1 --format csv  --parser.max-records 100000

  wgcf1:
    cap_add:
      - NET_ADMIN
    healthcheck:
      interval: 5s
      retries: 10
      test: curl -fs https://www.cloudflare.com/cdn-cgi/trace | grep -q -E 'warp=(on|plus)' && exit 0 || exit 1
      timeout: 45s
    image: neilpang/wgcf-docker:latest
    privileged: true
    restart: always
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    volumes:
      - ./service/wgcf1:/wgcf
      - /lib/modules:/lib/modules
      - /etc/localtime:/etc/localtime:ro

  parser2:
    build: ./
    depends_on:
      wgcf2:
        condition: service_healthy
    restart: "no"
    volumes:
      - ./:/code
    network_mode: service:wgcf2
    environment:
      - "TZ=Asia/Aqtau"
    stop_grace_period: 2m
    command: python3 -m parser_2gis --url /code/input2 --output /code/output2 --format csv  --parser.max-records 100000

  wgcf2:
    cap_add:
      - NET_ADMIN
    depends_on:
      wgcf1:
        condition: service_healthy
    healthcheck:
      interval: 5s
      retries: 10
      test: curl -fs https://www.cloudflare.com/cdn-cgi/trace | grep -q -E 'warp=(on|plus)' && exit 0 || exit 1
      timeout: 45s
    image: neilpang/wgcf-docker:latest
    privileged: true
    restart: always
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    volumes:
      - ./service/wgcf1:/wgcf
      - /lib/modules:/lib/modules
      - /etc/localtime:/etc/localtime:ro

  parser3:
    build: ./
    depends_on:
      wgcf3:
        condition: service_healthy
    restart: "no"
    network_mode: service:wgcf3
    volumes:
      - ./:/code
    environment:
      - "TZ=Asia/Aqtau"
    stop_grace_period: 2m
    command: python3 -m parser_2gis --url /code/input3 --output /code/output3 --format csv  --parser.max-records 100000

  wgcf3:
    cap_add:
      - NET_ADMIN
    depends_on:
      wgcf2:
        condition: service_healthy
    healthcheck:
      interval: 5s
      retries: 10
      test: curl -fs https://www.cloudflare.com/cdn-cgi/trace | grep -q -E 'warp=(on|plus)' && exit 0 || exit 1
      timeout: 45s
    image: neilpang/wgcf-docker:latest
    privileged: true
    restart: always
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    volumes:
      - ./service/wgcf1:/wgcf
      - /lib/modules:/lib/modules
      - /etc/localtime:/etc/localtime:ro

  parser4:
    build: ./
    depends_on:
      wgcf4:
        condition: service_healthy
    restart: "no"
    network_mode: service:wgcf4
    volumes:
      - ./:/code
    environment:
      - "TZ=Asia/Aqtau"
    stop_grace_period: 2m
    command: python3 -m parser_2gis --url /code/input4 --output /code/output4 --format csv  --parser.max-records 100000

  wgcf4:
    cap_add:
      - NET_ADMIN
    depends_on:
      wgcf3:
        condition: service_healthy
    healthcheck:
      interval: 5s
      retries: 10
      test: curl -fs https://www.cloudflare.com/cdn-cgi/trace | grep -q -E 'warp=(on|plus)' && exit 0 || exit 1
      timeout: 45s
    image: neilpang/wgcf-docker:latest
    privileged: true
    restart: always
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    volumes:
      - ./service/wgcf1:/wgcf
      - /lib/modules:/lib/modules
      - /etc/localtime:/etc/localtime:ro
  # parser5:
  #   build: ./
  #   restart: "no"
  #   volumes:
  #     - ./:/code
  #   environment:
  #     - "TZ=Asia/Aqtau"
  #   stop_grace_period: 2m
  #   command: python3 -m parser_2gis --url /code/input5 --output /code/output5 --format csv  --parser.max-records 100000

  # parser6:
  #   build: ./
  #   restart: "no"
  #   volumes:
  #     - ./:/code
  #   environment:
  #     - "TZ=Asia/Aqtau"
  #   stop_grace_period: 2m
  #   command: python3 -m parser_2gis --url /code/input6 --output /code/output6 --format csv  --parser.max-records 100000

  # parser7:
  #   build: ./
  #   restart: "no"
  #   volumes:
  #     - ./:/code
  #   environment:
  #     - "TZ=Asia/Aqtau"
  #   stop_grace_period: 2m
  #   command: python3 -m parser_2gis --url /code/input7 --output /code/output7 --format csv  --parser.max-records 100000

  # parser8:
  #   build: ./
  #   restart: "no"
  #   volumes:
  #     - ./:/code
  #   environment:
  #     - "TZ=Asia/Aqtau"
  #   stop_grace_period: 2m
  #   command: python3 -m parser_2gis --url /code/input8 --output /code/output8 --format csv  --parser.max-records 100000

  # parser9:
  #   build: ./
  #   restart: "no"
  #   volumes:
  #     - ./:/code
  #   environment:
  #     - "TZ=Asia/Aqtau"
  #   stop_grace_period: 2m
  #   command: python3 -m parser_2gis --url /code/input9 --output /code/output9 --format csv  --parser.max-records 100000

  # parser10:
  #   build: ./
  #   restart: "no"
  #   volumes:
  #     - ./:/code
  #   environment:
  #     - "TZ=Asia/Aqtau"
  #   stop_grace_period: 2m
  #   command: python3 -m parser_2gis --url /code/input10 --output /code/output10 --format csv  --parser.max-records 100000

  # parser11:
  #   build: ./
  #   restart: "no"
  #   volumes:
  #     - ./:/code
  #   environment:
  #     - "TZ=Asia/Aqtau"
  #   stop_grace_period: 2m
  #   command: python3 -m parser_2gis --url /code/input11 --output /code/output11 --format csv  --parser.max-records 100000

  # parser12:
  #   build: ./
  #   restart: "no"
  #   volumes:
  #     - ./:/code
  #   environment:
  #     - "TZ=Asia/Aqtau"
  #   stop_grace_period: 2m
  #   command: python3 -m parser_2gis --url /code/input12 --output /code/output12 --format csv  --parser.max-records 100000

  # parser13:
  #   build: ./
  #   restart: "no"
  #   volumes:
  #     - ./:/code
  #   environment:
  #     - "TZ=Asia/Aqtau"
  #   stop_grace_period: 2m
  #   command: python3 -m parser_2gis --url /code/input13 --output /code/output13 --format csv  --parser.max-records 100000

  # parser14:
  #   build: ./
  #   restart: "no"
  #   volumes:
  #     - ./:/code
  #   environment:
  #     - "TZ=Asia/Aqtau"
  #   stop_grace_period: 2m
  #   command: python3 -m parser_2gis --url /code/input14 --output /code/output14 --format csv  --parser.max-records 100000

  # parser15:
  #   build: ./
  #   restart: "no"
  #   volumes:
  #     - ./:/code
  #   environment:
  #     - "TZ=Asia/Aqtau"
  #   stop_grace_period: 2m
  #   command: python3 -m parser_2gis --url /code/input15 --output /code/output15 --format csv  --parser.max-records 100000

  # parser16:
  #   build: ./
  #   restart: "no"
  #   volumes:
  #     - ./:/code
  #   environment:
  #     - "TZ=Asia/Aqtau"
  #   stop_grace_period: 2m
  #   command: python3 -m parser_2gis --url /code/input16 --output /code/output16 --format csv  --parser.max-records 100000

  # parser17:
  #   build: ./
  #   restart: "no"
  #   volumes:
  #     - ./:/code
  #   environment:
  #     - "TZ=Asia/Aqtau"
  #   stop_grace_period: 2m
  #   command: python3 -m parser_2gis --url /code/input17 --output /code/output17 --format csv  --parser.max-records 100000

  # parser18:
  #   build: ./
  #   restart: "no"
  #   volumes:
  #     - ./:/code
  #   environment:
  #     - "TZ=Asia/Aqtau"
  #   stop_grace_period: 2m
  #   command: python3 -m parser_2gis --url /code/input18 --output /code/output18 --format csv  --parser.max-records 100000

  # parser19:
  #   build: ./
  #   restart: "no"
  #   volumes:
  #     - ./:/code
  #   environment:
  #     - "TZ=Asia/Aqtau"
  #   stop_grace_period: 2m
  #   command: python3 -m parser_2gis --url /code/input19 --output /code/output19 --format csv  --parser.max-records 100000

  # parser20:
  #   build: ./
  #   restart: "no"
  #   volumes:
  #     - ./:/code
  #   environment:
  #     - "TZ=Asia/Aqtau"
  #   stop_grace_period: 2m
  #   command: python3 -m parser_2gis --url /code/input20 --output /code/output20 --format csv  --parser.max-records 100000
